<a href="https://colab.research.google.com/github/smartinternz02/SI-GuidedProject-581944-1695907943/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = np.random.rand(4, 4)
df = pd.DataFrame(data, columns=['rv1', 'rv2', 'rv3', 'rv4'])
df

        rv1       rv2       rv3       rv4
0  0.018148  0.630466  0.666956  0.653451
1  0.217724  0.372802  0.048889  0.532870
2  0.233277  0.143625  0.077501  0.646567
3  0.935071  0.999845  0.413920  0.218100

In [ ]:
df.rename(columns={'rv1': 'Random value 1','rv2': 'Random value 2','rv3': 'Random value 3','rv4': 'Random value 4'}, inplace=True)

In [ ]:
dstats = df.describe()
dstats

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.169849        0.496871        0.271147        0.357482
std          0.293454        0.193314        0.282994        0.145420
min          0.013863        0.250124        0.023146        0.215746
25%          0.014742        0.389277        0.059458        0.240243
50%          0.027950        0.540492        0.213651        0.365076
75%          0.183056        0.648087        0.425340        0.482314
max          0.609632        0.656377        0.634138        0.484029

In [ ]:
df.isnull().sum()
df.dtypes

Random value 1    float64
Random value 2    float64
Random value 3    float64
Random value 4    float64
dtype: object

In [ ]:
df.iloc[:, 1]
df.iloc[:, 2]

0    0.355741
1    0.071562
2    0.023146
3    0.634138
Name: Random value 3, dtype: float64

In [ ]:
df['Random value 2']
df['Random value 3']

0    0.355741
1    0.071562
2    0.023146
3    0.634138
Name: Random value 3, dtype: float64